### ISSUE TITLE
New incoming users

### ISSUE THREAD

**Issue by LeO-Fr** [benji7425/discord-bot-activity-monitor#2]
Hello. I love your script, but something need to be changed:
I activated the option to add the role for users who speak but don't already have the role. It's perfect.
BUT: it's also add the role to new user BEFORE they talk, so the discord option to allow only confirmed email to talk is bypass because of the role who's added to new user before they talk. Can you fix this? Thank you!

**Comment by LeO-Fr** [comment]
Oh yeah I have the welcome messages turned on in my server.
Thank you for your advise, I will make sure the bot can't read the welcome channel.
Thank you! I think it's fix my problem, have a nice weekend.

**Comment by benji7425** [comment]
Glad to be able to help :)
